### ISSUE TITLE
No dist directory

### ISSUE THREAD

**Issue by jk-1** [yahoo/intl-messageformat-parser#14]
Version 1.2.0

Your usage documentation says:
>Loading in the Browser
>The dist/ folder contains the version of this package for use in the browser, and it can be loaded and >used like this:

However, there is no dist folder in v1.2.0 download zip.
v1.2.0 is not yet available in webjars.org but v1.1.0 is and the dist folder is available there, see link
http://www.webjars.org/listfiles/org.webjars.npm/intl-messageformat-parser/1.1.0

**Comment by caridy** [comment]
`dist/` folder is in the tarball for npm. You can build the project manually as well to generate it, but the built files are not committed into git.
