### ISSUE TITLE
Bower

### ISSUE THREAD

**Issue by brettz9** [yahoo/intl-messageformat-parser#9]
Could you release this with Bower?

**Comment by caridy** [comment]
we have decided a while ago to drop bower support, feel free to create a new repo that uses this library thru bower.

**Comment by brettz9** [comment]
I tried registering through Bower with "intl-messageformat" but it said it was a duplicate package (though that string also doesn't show up when searching Bower). Do you want to [unregister](http://bower.io/docs/creating-packages/#unregister) or have me rename?

**Comment by caridy** [comment]
Oh, right, that was probably @jasonmit or @ericf, can you help unregister these pkgs? Apparently, I have no right to do it.

**Comment by brettz9** [comment]
Sorry, I guess I should have been requesting this at the main "intl-messageformat" project instead of here. For those who have the credentials, it really should take just two seconds to unregister if you follow the steps at http://bower.io/docs/creating-packages/#unregister  ...

**Comment by jasonmit** [comment]
I don't see any projects registered under intl-messageformat*

http://bower.io/search/?q=intl-messageformat

**Comment by brettz9** [comment]
Thanks very much, I was able to successfully re-register! FYI, the Bower search is still not showing it for me, but I was able to have the package auto-installed as a dependency (and I have seen this happen with the Bower website before, as it has some caching issues or something).

I don't know, however, why it was not showing up earlier on the Bower website (even before I reported this issue), but hopefully it will be there shortly.

It is nice to have a pretty universal i18n solution available in my environment of choice. Thanks again!

**Comment by caridy** [comment]
@brettz9 please, send a PR with some updates to the docs to add a link to the bower support you're providing.

**Comment by brettz9** [comment]
Should I add an "install" section to the README with reference to npm and bower, with the caveat that the latter is third-party maintained, etc.?

And while I'm at it, should I fix the browser paths in the README to refer to "dist"?

Speaking of docs, were you ok with what I added at https://github.com/yahoo/intl-messageformat/wiki ?

**Comment by caridy** [comment]
> Should I add an "install" section to the README with reference to npm and bower, with the caveat that the latter is third-party maintained, etc.?

yes, that should be enough.

> And while I'm at it, should I fix the browser paths in the README to refer to "dist"?

what path?

> Speaking of docs, were you ok with what I added at https://github.com/yahoo/intl-messageformat/wiki ?

please, remove it, we don't use wiki in these repos, just the readme.

**Comment by brettz9** [comment]
As far as the path, for example, in the section "Loading Intl MessageFormat in a browser", you include the tag `<script src="intl-messageformat/intl-messageformat.min.js"></script>`, but the file is actually within the "dist" folder. Likewise elsewhere and with the Intl polyfill too. Surely most of us can figure it out, but it helps people get on the right footing when they are not worrying that they missed a build step or something when they can't find the specified file at the indicated path.

I removed the reference I had added from the wiki, replacing it with the text "Empty" as the wiki was not allowing me to enter it blank. You can disable the wiki under the repo settings. But do you not want to refer anywhere to libraries using intl-messageformat ? Some users may find it convenient.
